# Generated by Django 3.2.8 on 2021-11-06 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211031_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaywish',
            old_name='text',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='_id'),
        ),
    ]
